function [R0_table] = scaling_to_R0(china_R0,file_loc)
% scaling_to_R0 imports a table of scaling factors generated by one of the
% estimate_scaling_by_country... scripts and generates a table of estimated
% R0 values given an estimate china_R0 of the basic reproductive ratio in
% China.

T = readtable(file_loc);

R0 = china_R0*T.ScalingFactor;

R0_table = table(T.Country,R0);
R0_table.Properties.VariableNames(2) = {'Estimated R0'};

end